#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require __DIR__ . '/SDaiLover.php';

$config = require __DIR__ . '/config/console.php';

$application = SDaiLover::createConsoleApplication($config);
$exitCode = $application->run();
exit($exitCode);